/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 74a1052eb6e9eb7a69804c0db45896df)
interface __BaseEnv_Env {
	FRONTEND_ORIGIN: "https://splitdecision.planitnow.us";
	ROOMS: DurableObjectNamespace<import("./worker/src/index").GameRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/src/index");
		durableNamespaces: "GameRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "FRONTEND_ORIGIN">> {}
}
